return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Not a chance.",
			GENERIC = "Not doing it.",
			NOBITS = "Literally nothing.",
		},
		STORE =
		{
			GENERIC = "There's too much stuff.",
			NOTALLOWED = "I can't put that in there!.",
			INUSE = "Hurry up and finish!",
		},
		RUMMAGE =
		{	
			GENERIC = "I can't do that.",
			INUSE = "I should probably wait.",	
		},
        COOK =
        {
            GENERIC = "What's even cooking?.",
            INUSE = "Get on with it!",
        },
	},
	ACTIONFAIL_GENERIC = "I can't do that.",
	ANNOUNCE_ADVENTUREFAIL = "That went terribly.",
	ANNOUNCE_BEES = "Continue doing that...",
	ANNOUNCE_BOOMERANG = "Ouch! Ow. Owww.",
	ANNOUNCE_CHARLIE = "Something's going to try and kill me. Again.",
	ANNOUNCE_CHARLIE_ATTACK = "CALLED IT.",
	ANNOUNCE_COLD = "It's cold as balls...",
	ANNOUNCE_CRAFTING_FAIL = "I don't have everything I need.",
	ANNOUNCE_DEERCLOPS = "That doesn't sound good.",
	ANNOUNCE_DUSK = "Night is coming.",
	ANNOUNCE_EAT =
	{
		GENERIC = "That was edible at least.",
		PAINFUL = "I Probably shouldn't have eaten that...",
		SPOILED = "Ew! That was gross...",
		STALE = "I think that was starting to turn.",
	},
	ANNOUNCE_ENTER_DARK = "It's as dark as my metaphorical heart!",
	ANNOUNCE_ENTER_LIGHT = "Aww.",
	ANNOUNCE_FREEDOM = "Sweet! I'm out of here!",
	ANNOUNCE_HIGHRESEARCH = "I always knew I was smart.",
	ANNOUNCE_HOUNDS = "Cerberus? Is that you??",
	ANNOUNCE_HUNGRY = "Hungryyy!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Getting close.",
	ANNOUNCE_HUNT_LOST_TRAIL = "It's gone.",
	ANNOUNCE_INV_FULL = "My pockets are full!",
	ANNOUNCE_KNOCKEDOUT = "Oooo...",
	ANNOUNCE_LOWRESEARCH = "Didn't get much out of that.",
	ANNOUNCE_MOSQUITOS = "YOU GUYS ARE INSUFFERABLE!",
	ANNOUNCE_NODANGERSLEEP = "Not a chance - I value my life.",
	ANNOUNCE_NODAYSLEEP = "It's too bright.",
	ANNOUNCE_NODAYSLEEP_CAVE = "I'm not tired.",
	ANNOUNCE_NOHUNGERSLEEP = "I'm too hungry.",
	ANNOUNCE_NODANGERAFK = "Now's not the time!",
	ANNOUNCE_NO_TRAP = "That was easy.",
	ANNOUNCE_PECKED = "Ow! Back off!",
	ANNOUNCE_QUAKE = "That doesn't sound good.",
	ANNOUNCE_RESEARCH = "I can hear my mortal brain working. It's too loud.",
	ANNOUNCE_THORNS = "Ow!",
	ANNOUNCE_TORCH_OUT = "Welp, that's not good. Here I am, Charlie!",
	ANNOUNCE_TRAP_WENT_OFF = "Oopsie.",
	ANNOUNCE_UNIMPLEMENTED = "I don't think it's ready yet.",
	ANNOUNCE_WORMHOLE = "That was AMAZING!",
	ANNOUNCE_CANFIX = "I don't think I can do that.",
	ANNOUNCE_ACCOMPLISHMENT = "Nice.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "If only my friends could see me now... I miss the other place.",	
	ANNOUNCE_BECOMEGHOST = "ooOOoooOOOoOooo!!",
	ANNOUNCE_GHOSTDRAIN = "God damn losers can't stay alive, geez.",

	DESCRIBE_SAMECHARACTER = "... You look like me. YOU MUST DIE.",
	
	BATTLECRY =
	{
		GENERIC = "GET 'IM, GET 'IM!!",
		PIG = "Here piggy piggy! Death beckons you~...",
		PREY = "Die time...!",
		SPIDER = "You know death? Yeah, it called.",
		SPIDER_WARRIOR = "Better you than me!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "I have better things to do. Like watch grass grow.",
		PIG = "I'll let him go. This time.",
		PREY = "Slippery scoundrel.",
		SPIDER = "He's too gross, anyway.",
		SPIDER_WARRIOR = "Shoo, you nasty thing!",
	},
	DESCRIBE =
	{
        PLAYER =
        {
            GENERIC = "It's that one nerd, %s!",
            ATTACKER = "That %s looks shifty...",
            MURDERER = "Screw you!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart. Too bad I don't have one.",
        },
		WILSON = 
		{
			GENERIC = "It's Wilson!",
			ATTACKER = "That Wilson looks shifty...",
			MURDERER = "Murderer!",
			REVIVER = "Wilson, friend of ghosts.",
			GHOST = "Wilson could use a heart.",
		},
		WOLFGANG = 
		{
			GENERIC = "It's Wolfgang!",
			ATTACKER = "That Wolfgang looks shifty...",
			MURDERER = "Murderer!",
			REVIVER = "Wolfgang, friend of ghosts.",
			GHOST = "Wolfgang could use a heart.",
		},
		WAXWELL = 
		{
			GENERIC = "It's Maxwell!",
			ATTACKER = "That Maxwell looks shifty...",
			MURDERER = "Murderer!",
			REVIVER = "Maxwell, friend of ghosts.",
			GHOST = "Maxwell could use a heart.",
		},
		WX78 = 
		{
			GENERIC = "It's WX-78!",
			ATTACKER = "That WX-78 looks shifty...",
			MURDERER = "Murderer!",
			REVIVER = "WX-78, friend of ghosts.",
			GHOST = "WX-78 could use a heart.",
		},
		WILLOW = 
		{
			GENERIC = "It's Willow!",
			ATTACKER = "That Willow looks shifty...",
			MURDERER = "Murderer!",
			REVIVER = "Willow, friend of ghosts.",
			GHOST = "Willow could use a heart.",
		},
		WENDY = 
		{
			GENERIC = "It's Wendy!",
			ATTACKER = "That Wendy looks shifty...",
			MURDERER = "Murderer!",
			REVIVER = "Wendy, friend of ghosts.",
			GHOST = "Wendy could use a heart.",
		},
		WOODIE = 
		{
			GENERIC = "It's Woodie!",
			ATTACKER = "That Woodie looks shifty...",
			MURDERER = "Murderer!",
			REVIVER = "Woodie, friend of ghosts.",
			GHOST = "Woodie could use a heart.",
		},
		WICKERBOTTOM = 
		{
			GENERIC = "It's Wickerbottom!",
			ATTACKER = "That Wickerbottom looks shifty...",
			MURDERER = "Murderer!",
			REVIVER = "Wickerbottom, friend of ghosts.",
			GHOST = "Wickerbottom could use a heart.",
		},
		WES = 
		{
			GENERIC = "It's Wes!",
			ATTACKER = "That Wes looks shifty...",
			MURDERER = "Murderer!",
			REVIVER = "Wes, friend of ghosts.",
			GHOST = "Wes could use a heart.",
		},
		MULTIPLAYER_PORTAL = "Fashion after function I suppose.",
		WORMLIGHT = "Looks delicious.",
		WORM =
		{
		    PLANT = "Seems safe to me.",
		    DIRT = "Is dirt supposed to move or...?",
		    WORM = "It's a worm!",
		},

		EEL = "This could taste nice cooked. Key word: 'could'.",
		EEL_COOKED = "Smells great...",
		UNAGI = "I cooked it myself! I'm surprised it didn't explode.",
		EYETURRET = "I hope it doesn't turn on me.",
		EYETURRET_ITEM = "I think it's sleeping.",
		MINOTAURHORN = "Wow! I'm glad that didn't gore me!",
		MINOTAURCHEST = "It may contain a bigger something fantastic! Or horrible. Either or.",
		THULECITE_PIECES = "Just some chunks of thulectite.",
		POND_ALGAE = "Pond algae.",
		GREENSTAFF = "Destruction is my forte.",
		POTTEDFERN = "A fern in a pot.",

		THULECITE = "Not seen this before. It must be native.",
		ARMORRUINS = "It's not that heavy, surprisingly.",
		RUINS_BAT = "It has quite a heft to it.",
		RUINSHAT = "Fit for a king. Or me.",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "All is well.",
		WARN = "Getting pretty magical around here.",
		WAXING = "I think it's becoming more concentrated!",
		STEADY = "We're going steady.",
		WANING = "My flux says it's less powerful.",
		DAWN = "The nightmare is pretty much gone.",
		NOMAGIC = "There's no magic around here.",
		},
		BISHOP_NIGHTMARE = "It's falling apart!",
		ROOK_NIGHTMARE = "Spooky.",
		KNIGHT_NIGHTMARE = "It's a knightmare!",
		MINOTAUR = "That thing doesn't look happy.",
		SPIDER_DROPPER = "Note to self: Don't look up.",
		NIGHTMARELIGHT = "Bright.",
		GREENGEM = "It's green and gemmy. Impressive.",
		RELIC = "Ancient household goods of little value.",
		RUINS_RUBBLE = "This can be fixed. Maybe.",
		MULTITOOL_AXE_PICKAXE = "Oooooooo!",
		ORANGESTAFF = "Hooray for laziness.",
		YELLOWAMULET = "Better than a torch.",
		GREENAMULET = "Cost effective!",
		SLURPERPELT = "It's dead?",	

		SLURPER = "Mother?",
		SLURPER_PELT = "It's dead?",
		ARMORSLURPER = "It's soggy...",
		ORANGEAMULET = "Teleportation can be so useful.",
		YELLOWSTAFF = "Putting gems on sticks make magic. Noted.",
		YELLOWGEM = "Oh, right. The yellow gem. It's yellow and is a gem.",
		ORANGEGEM = "Oh, right. The orange gem. It's orange and is a gem",
		TELEBASE = 
		{
			VALID = "It's ready to go.",
			GEMS = "It needs more purple gems.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks ready.",
			GEMS = "It needs a gem.",
		},
		STAFFLIGHT = "This could be really dangerous if in the wrong hands. How unfortunate for the world I've got it.",
		RESEARCHLAB4 = "How is that even pronounced? Mortals and their weird languages, geez.",
	
        ANCIENT_ALTAR = "I last saw this in '02. 1302 BC.",

        ANCIENT_ALTAR_BROKEN = "Seeing how old this is I'm not surprised it's broken.",

        ANCIENT_STATUE = "An old statue.",

        LICHEN = "A kind of moss.",
		CUTLICHEN = "Doesn't last long.",

		CAVE_BANANA = "I can't stand bananas.",
		CAVE_BANANA_COOKED = "Euch.",
		CAVE_BANANA_TREE = "It's dubiously photosynthetical.",
		ROCKY = "How is it even alive...?",
		
		COMPASS =
		{
			GENERIC="I can't get a reading.",
			N = "North",
			S = "South",
			E = "East",
			W = "West",
			NE = "Northeast",
			SE = "Southeast",
			NW = "Northwest",
			SW = "Southwest",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "I think it's becoming more concentrated!",
			STEADY = "It seems to be staying steady.",
			WANING = "Feels like it's receding.",
			DAWN = "The nightmare is almost gone!",
			WARN = "Getting pretty magical around here.",
			CALM = "All is well.",
			NOMAGIC = "There's no magic around here.",
		},

		HOUNDSTOOTH="It's sharp, like my tongue.",
		ARMORSNURTLESHELL="It's sticky....",
		BAT="Oh my goodness! Father?",
		BATBAT = "I wonder if I could fly if I had two of these.",
		BATWING="Could be nice cooked.",
		BATWING_COOKED="Looks tasty!",
		BEDROLL_FURRY="Looks warm.",
		BUNNYMAN="I am filled with an irresistible urge to kill. Damn vegans.",
		FLOWER_CAVE="Science makes it glow.",
		FLOWER_CAVE_DOUBLE="Science makes it glow.",
		FLOWER_CAVE_TRIPLE="Science makes it glow.",
		GUANO="Another flavour of poop.",
		LANTERN="A more civilized torch. Wouldn't expect humans to know about it, though.",
		LIGHTBULB="Interesting.",
		MANRABBIT_TAIL="I just like holding it. It's fuzzy.",
		MUSHTREE_TALL  ="That mushroom got too big for its own good.",
		MUSHTREE_MEDIUM="It reminds me of the fairy massacre of 1343 BC.",
		MUSHTREE_SMALL ="A larger mushroom.",
		RABBITHOUSE="That's not a real carrot.",
		SLURTLE="Slimy and gross, like my good friend Krosto.",
		SLURTLE_SHELLPIECES="A puzzle with no solution.",
		SLURTLEHAT="I hope it doesn't mess up my hair.",
		SLURTLEHOLE="A den of 'ew'.",
		SLURTLESLIME="If it wasn't useful, I wouldn't even touch it.",
		SNURTLE="He's less gross, but still gross.",
		SPIDER_HIDER="More spiders? This is just unreasonable.",
		SPIDER_SPITTER="They like my cousin Jeff.",
		SPIDERHOLE="It's encrusted with old webbing.",
		STALAGMITE="Looks like a rock to me.",
		STALAGMITE_FULL="Looks like a rock to me.",
		STALAGMITE_LOW="Looks like a rock to me.",
		STALAGMITE_MED="Looks like a rock to me.",
		STALAGMITE_TALL="Rocks, rocks, rocks, rocks...",
		STALAGMITE_TALL_FULL="Rocks, rocks, rocks, rocks...",
		STALAGMITE_TALL_LOW="Rocks, rocks, rocks, rocks...",
		STALAGMITE_TALL_MED="Rocks, rocks, rocks, rocks...",

		TURF_CARPETFLOOR = "Yet another ground type.",
		TURF_CHECKERFLOOR = "Yet another ground type.",
		TURF_DIRT = "Yet another ground type.",
		TURF_FOREST = "Yet another ground type.",
		TURF_GRASS = "Yet another ground type.",
		TURF_MARSH = "Yet another ground type.",
		TURF_ROAD = "Yet another ground type.",
		TURF_ROCKY = "Yet another ground type.",
		TURF_SAVANNA = "Yet another ground type.",
		TURF_WOODFLOOR = "Yet another ground type.",

		TURF_CAVE="Yet another ground type.",
		TURF_FUNGUS="Yet another ground type.",
		TURF_SINKHOLE="Yet another ground type.",
		TURF_UNDERROCK="Yet another ground type.",
		TURF_MUD="Yet another ground type.",

		POWCAKE = "I don't think if I'm desperate enough... Yet.",
        CAVE_ENTRANCE = 
        {
            GENERIC="I wonder if I could move that rock.",
            OPEN = "I bet there's all sorts of things to discover down there.",
        },
        CAVE_EXIT = "I've had enough discovery for now.",
		MAXWELLPHONOGRAPH = "So that's where the music was coming from.",
		BOOMERANG = "Aerodynamical!",
		PIGGUARD = "He doesn't look as friendly as the others.",
		ABIGAIL = "She looks cute. Less so than me, but still cute.",
		ADVENTURE_PORTAL = "Never again. Winter wonderland? As if.",
		AMULET = "Resurrection is a necessary precaution.",
		ANIMAL_TRACK = "Tracks left by food. I mean... an animal.",
		ARMORGRASS = "I hope there are no bugs in this.",
		ARMORMARBLE = "This feels really heavy...",
		ARMORWOOD = "Feels secure enough.",
		ARMOR_SANITY = "Wearing this makes me feel safe and insecure.",
		ASH =
		{
			GENERIC = "All that's left after fire has done its job. I like.",
			REMAINS_EYE_BONE = "The eyebone was consumed by fire when I teleported!",
			REMAINS_THINGIE = "This was once a thing before it got burned...",
		},
		AXE = "A cutting tools used by mortals incapable of detonations. I don't like using it.",
		BABYBEEFALO = "It'd be cute if it didn't look like it does.",
		BACKPACK = "It's for me to put my stuff in.",
		BACONEGGS = "I cooked it myself!",
		BANDAGE = "Seems sterile enough for this flimsy fleshy body.",
		BASALT = "That's too strong to break through with this mortal husk. I am disappoint.",
		BATBAT = "I bet I could fly if I held two of these.",
		BEARDHAIR = "I made them with my face.",
		BEDROLL_STRAW = "It smells like wet.",
		BEE =
		{
			GENERIC = "To bee or not to bee.",
			HELD = "Stingy.",
		},
		BEEBOX =
		{
			FULLHONEY = "It's full of honey.",
			GENERIC = "Bees!",
			NOHONEY = "It's empty.",
			SOMEHONEY = "I should wait a bit.",
		},
		BEEFALO =
		{
			FOLLOWER = "He's coming along peacefully.",
			GENERIC = "It's a beefalo!",
			NAKED = "Aww, he's so sad.",
			SLEEPING = "These guys are really heavy sleepers...",
		},
		BEEFALOHAT = "What a nice hat.",
		BEEFALOWOOL = "It smells like beefalo tears.",
		BEEHAT = "This should keep me protected.",
		BEEHIVE = "It's buzzing with activity.",
		BEEMINE = "It buzzes when I shake it.",
		BEEMINE_MAXWELL = "Bottled mosquito rage!",
		BERRIES = "Blueberries are better.",
		BERRIES_COOKED = "I don't think heat improved them.",
		BERRYBUSH =
		{
			BARREN = "I think it needs to be fertilized.",
			GENERIC = "Blueberries are better.",
			PICKED = "Maybe they'll grow back?",
		},
		BIRDCAGE =
		{
			GENERIC = "I should put a bird in it.",
			OCCUPIED = "That's my bird!",
			SLEEPING = "Awwww, he's asleep.",
		},
		BIRDTRAP = "Gives me a net advantage!",
		BIRD_EGG = "A small, normal egg.",
		BIRD_EGG_COOKED = "Sunny side yum!",
		BISHOP = "Back off, preacherman!",
		BLOWDART_FIRE = "This seems relatively safe if you don't include the dangers.",
		BLOWDART_SLEEP = "I'll save it for the beefalos.",
		BLOWDART_PIPE = "Good practice for the fires Joan makes!",
		BLUEAMULET = "Cool as ice!",
		BLUEGEM = "It sparkles with cold energy.",
		BLUEPRINT = "It's scientific!",
		BLUE_CAP = "It's weird and gooey. Like Krosto.",
		BLUE_CAP_COOKED = "It's different now...",
		BLUE_MUSHROOM =
		{
			GENERIC = "It's a mushroom.",
			INGROUND = "It's sleeping.",
			PICKED = "I wonder if it will come back?",
		},
		BOARDS = "Wooden boards.",
		BOAT = "Is that how I got here?",
		BONESTEW = "Very filling.",
		BUGNET = "For catching bugs. You'd think that'd be obvious.",
		BUSHHAT = "It's kind of scratchy, but I'm keeping it to spite Joan.",
		BUTTER = "I can't believe it's not butter!",
		BUTTERFLY =
		{
			GENERIC = "Butterfly, flutter by.",
			HELD = "She had it coming.",
		},
		BUTTERFLYMUFFIN = "Fly away.",
		BUTTERFLYWINGS = "Without these, it's just a butter.",
		CAMPFIRE =
		{
			EMBERS = "I should put something on the fire before it goes out.",
			GENERIC = "Sure beats darkness.",
			HIGH = "Reminds me of home...",
			LOW = "The fire's getting a bit low.",
			NORMAL = "Nice and comfy.",
			OUT = "Well, that's over.",
		},
		CANE = "A quick way to a faster new you!",
		CARROT = "Yuck. It's all vegetabley.",
		CARROT_COOKED = "Mushy.",
		CARROT_PLANTED = "The earth is making plantbabies.",
		CARROT_SEEDS = "It's a seed. Impressive.",
		CAVE_FERN = "It's a fern. Incredible.",
		CHARCOAL = "Thanks, Joan.",
        CHESSJUNK1 = "A pile of broken chess pieces.",
        CHESSJUNK2 = "Another pile of broken chess pieces.",
        CHESSJUNK3 = "Even more broken chess pieces.",
		CHESTER = "You sound a bit chesty there, you should get that looked at.",
		CHESTER_EYEBONE =
		{
			GENERIC = "It's looking at me.",
			WAITING = "It went to sleep.",
		},
		COOKEDMANDRAKE = "It's screams amuse me.",
		COOKEDMEAT = "Char broiled to perfection.",
		COOKEDMONSTERMEAT = "That's only somewhat more appetizing than when it was raw.",
		COOKEDSMALLMEAT = "Now I don't have to worry about getting worms!",
		COOKPOT =
		{
			COOKING_LONG = "This is going to take a while.",
			COOKING_SHORT = "It's almost done!",
			DONE = "It's ready to eat!",
			EMPTY = "It makes me hungry just to look at it.",
		},
		CORN = "High in fructose!",
		CORN_COOKED = "High in fructose!",
		CORN_SEEDS = "It's a seed.",
		CROW =
		{
			GENERIC = "People are too superstitious.",
			HELD = "He doesn't look too happy there. I can relate.",
		},
		CUTGRASS = "Cut grass, ready for arts and crafts.",
		CUTREEDS = "Cut reeds, ready for ... I can't rhyme that.",
		CUTSTONE = "I've made them seductively smooth.",
		DEADLYFEAST = "A most potent dish.",
		DEERCLOPS = "It's enormous!!",
		DEERCLOPS_EYEBALL = "This is really gross. I like it.",
		DEPLETED_GRASS =
		{
			GENERIC = "It's a tuft of grass.",
		},
		DEVTOOL = "It smells of bacon!",
		DEVTOOL_NODEV = "I'm not strong enough to wield it.",
		DIRTPILE = "It's a pile of dirt... or IS it?",
		DIVININGROD =
		{
			COLD = "The signal is very faint.",
			GENERIC = "It's some kind of homing device.",
			HOT = "This thing's going crazy!",
			WARM = "I'm headed in the right direction.",
			WARMER = "I must be getting pretty close.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "I wonder what it does.",
			READY = "It looks like it needs a large key.",
			UNLOCKED = "Now my machine can work!",
		},
		DIVININGRODSTART = "That rod looks useful.",
		DRAGONFRUIT = "What a weird fruit.",
		DRAGONFRUIT_COOKED = "Still weird.",
		DRAGONFRUIT_SEEDS = "It's a seed.",
		DRAGONPIE = "I cooked it myself!",
		DRUMSTICK = "I should gobble it.",
		DRUMSTICK_COOKED = "Now it's even tastier.",
		DUG_BERRYBUSH = "I should plant this.",
		DUG_GRASS = "I should plant this.",
		DUG_MARSH_BUSH = "I should plant this.",
		DUG_SAPLING = "I should plant this.",
		DURIAN = "Oh it smells!",
		DURIAN_COOKED = "Now it smells even worse!",
		DURIAN_SEEDS = "It's a seed.",
		EARMUFFSHAT = "At least my ears won't get cold...",
		EGGPLANT = "It doesn't look like an egg.",
		EGGPLANT_COOKED = "It's even less eggy.",
		EGGPLANT_SEEDS = "It's a seed.",
		EVERGREEN =
		{
			BURNING = "What a waste of wood.",
			BURNT = "I feel like I could have prevented that. Wait, no, nevermind.",
			CHOPPED = "Take that, nature!",
			GENERIC = "It's all Piney.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "What a waste of wood.",
			BURNT = "I feel like I could have prevented that. Wait, no, nevermind.",
			CHOPPED = "Take that, nature!",
			GENERIC = "This sad tree has no cones.",
		},
		EYEPLANT = "I think I'm being watched.",
		FARMPLOT =
		{
			GENERIC = "I should try planting some crops.",
			GROWING = "Go plants go!",
			NEEDSFERTILIZER = "I think it needs to be fertilized.",
		},
		FEATHERHAT = "Be the bird!",
		FEATHER_CROW = "A crow feather.",
		FEATHER_ROBIN = "A redbird feather.",
		FEATHER_ROBIN_WINTER = "A snowbird feather.",
		FEM_PUPPET = "She's trapped!",
		FIREFLIES =
		{
			GENERIC = "If only I could catch them!",
			HELD = "They make my pocket glow!",
		},
		FIREHOUND = "Looking hot.",
		FIREPIT =
		{
			EMBERS = "I should put something on the fire before it goes out.",
			GENERIC = "Sure beats darkness.",
			HIGH = "Reminds me of home!",
			LOW = "The fire's getting a bit low.",
			NORMAL = "Nice and comfy.",
			OUT = "At least I can start it up again.",
		},
		FIRESTAFF = "I don't want to set the world on fire... I lied, sorry.",

		FISH = "No proverbs needed here, Jesus!",
		FISHINGROD = "Used for catching proverbs.",
		FISHSTICKS = "Looks sticky.",
		FISHTACOS = "I cooked it myself!",
		FISH_COOKED = "Grilled to perfection.",
		FLINT = "It's a very sharp rock.",
		FLOWER = "It's pretty but it smells like a common labourer.",
		FLOWERHAT = "Don't I already have one of these?",
		FLOWER_EVIL = "I prefer this kind.",
		FOLIAGE = "Some leafy greens.",
		FOOTBALLHAT = "I don't like sports.",
		FROG =
		{
			DEAD = "He's croaked.",
			GENERIC = "Devils they are.",
			SLEEPING = "Aww, look at him sleep! So vulnerable to bloody death!",
		},
		FROGGLEBUNWICH = "I cooked it myself!",
		FROGLEGS = "First of all, gross.",
		FROGLEGS_COOKED = "I dislike this.",
		FRUITMEDLEY = "I... Am.... FRUIT!!",
		GEARS = "A pile of mechanical parts.",
		GHOST = "It looks like me, just whiter and less gaseous.",
		GOLDENAXE = "That's one fancy axe.",
		GOLDENPICKAXE = "Isn't gold really soft?",
		GOLDENPITCHFORK = "The ground will be flattered.",
		GOLDENSHOVEL = "I can't wait to dig holes. Wait... I'm no dwarf!",
		GOLDNUGGET = "Wish it were chicken.",
		GRASS =
		{
			BARREN = "It needs poop.",
			BURNING = "Preeettty!",
			GENERIC = "It's a tuft of grass. Wooow.",
			PICKED = "I cut it down in the prime of its life.",
		},
		GREEN_CAP = "It seems pretty normal.",
		GREEN_CAP_COOKED = "It's different now...",
		GREEN_MUSHROOM =
		{
			GENERIC = "It's a mushroom.",
			INGROUND = "It's sleeping.",
			PICKED = "I wonder if it will come back?",
		},
		GUNPOWDER = "It looks like pepper. Maybe you should try eating some?",
		HAMBAT = "Tasty!.",
		HAMMER = "Stop! It's time! To hammer things!",
		HEALINGSALVE = "The stinging means that it's working. I think.",
		HEATROCK =
		{
			COLD = "It's stone cold. Because it's a stone.",
			GENERIC = "I could heat this up near the fire.",
			HOT = "Nice and toasty hot!",
			WARM = "It's warm and cuddly... for a rock!",
		},
		HOME = "Someone must live here.",
		HOMESIGN = "It says 'You are here'.",
		HONEY = "Looks delicious! I think.",
		HONEYCOMB = "Bees used to live in this. Wow, I feel like Mr Columbus.",
		HONEYHAM = "I cooked it myself!",
		HONEYNUGGETS = "I cooked it myself!",
		HORN = "It sounds like a beefalo field in there.",
		HOUND = "You ain't nothing, hound dog!",
		HOUNDBONE = "Creepy.",
		HOUNDMOUND = "I wouldn't want to pick a bone with the owner. Or maybe I would.",
		ICEBOX = "I have harnessed the power of cold!",
		ICEHOUND = "Are there hounds for every season? This is absurd.",
		INSANITYROCK =
		{
			ACTIVE = "TAKE THAT, SANE SELF!",
			INACTIVE = "It's more of a pyramid than an obelisk.",
		},
		JAMMYPRESERVES = "I cooked it myself!",
		KABOBS = "I cooked it myself!",
		KILLERBEE =
		{
			GENERIC = "That bee doesn't look happy.",
			HELD = "Why would I do this again?",
		},
		KNIGHT = "Check it out!",
		KOALEFANT_SUMMER = "Adorably delicious.",
		KOALEFANT_WINTER = "It looks warm and full of meat.",
		KRAMPUS = "He's going after my stuff!",
		KRAMPUS_SACK = "Ew. It has Krampus slime all over it.",
		LEIF = "Size matters, and he has lots of wood!",
		LEIF_SPARSE = "Size matters, and he has lots of wood!",
		LIGHTNING_ROD =
		{
			CHARGED = "The power is mine!",
			GENERIC = "I can harness the heavens! Take that, Jesus!",
		},
		LITTLE_WALRUS = "Eww... He's all hairy.",
		LIVINGLOG = "It looks worried. I'm not surprised.",
		LOCKEDWES = "Maxwell's statues are trapping him.",
		LOG =
		{
			BURNING = "That's some hot wood!",
			GENERIC = "It's big, it's heavy, and it's wood.",
		},
		LUREPLANT = "It's so alluring.",
		LUREPLANTBULB = "Now I can start my very own meat farm.",
		MALE_PUPPET = "He's trapped!",
		MANDRAKE =
		{
			DEAD = "A mandrake root has strange powers.",
			GENERIC = "I've heard strange things about those plants.",
			PICKED = "Stop following me!",
		},
		MANDRAKESOUP = "I cooked it myself!",
		MANDRAKE_COOKED = "It doesn't seem so strange anymore.",
		MARBLE = "Fancy!",
		MARBLEPILLAR = "I think I could use that.",
		MARBLETREE = "I don't think an axe will cut it.",
		MARSH_BUSH =
		{
			BURNING = "That's burning fast!",
			GENERIC = "It looks thorny.",
			PICKED = "That hurt.",
		},
		MARSH_PLANT = "It's a plant.",
		MARSH_TREE =
		{
			BURNING = "Spikes and fire!",
			BURNT = "Now it's burnt and spiky.",
			CHOPPED = "Not so spiky now!",
			GENERIC = "Those spikes look sharp!",
		},
		MAXWELL = "I respect him, but detest his choices.",
		MAXWELLHEAD = "I can see into his pores.",
		MAXWELLLIGHT = "I wonder how they work.",
		MAXWELLLOCK = "Looks almost like a key hole.",
		MAXWELLTHRONE = "That doesn't look very comfortable.",
		MEAT = "It's a bit gamey, but it'll do.",
		MEATBALLS = "I cooked it myself!",
		MEATRACK =
		{
			DONE = "Jerky time!",
			DRYING = "Meat takes a while to dry.",
			GENERIC = "I should dry some meats.",
		},
		MEAT_DRIED = "Just jerky enough.",
		MERM = "Smells fishy!",
		MERMHEAD = "That's rather disgusting.",
		MERMHOUSE = "Who would live here? Probably cousin Joe.",
		MINERHAT = "This will keep my hands free.",
		MONKEY = "Curious.",
		MONKEYBARREL = "Did that just move?",
		MONSTERLASAGNA = "Yay! I cooked some pointless food!",
		MONSTERMEAT = "Ugh. I don't think I should eat that.",
		MONSTERMEAT_DRIED = "Strange-smelling jerky.",
		MOSQUITO =
		{
			GENERIC = "Yeah... nah....",
			HELD = "Hey, is that my blood...?",
		},
		MOSQUITOSACK = "It's probably not someone else's blood...",
		MOUND =
		{
			DUG = "I should probably feel bad about that.",
			GENERIC = "I bet there's all sorts of good stuff down there!",
		},
		NIGHTLIGHT = "It gives off a spooky light.",
		NIGHTMAREFUEL = "Is this essence?",
		NIGHTSWORD = "A potent weapon.",
		NITRE = "I'm no geologist, but this looks pretty useless to me.",
		ONEMANBAND = "Using this would be insane.",
		PANDORASCHEST = "It may contain something fantastic! Or horrible.",
		PANFLUTE = "I can serenade the animals.",
		PAPYRUS = "Paper similar to that of the ancient Egyptians. I would know, I was there.",
		PENGUIN = "Must be breeding season.",
		PERD = "Death approaches thee!",
		PEROGIES = "I cooked it myself!",
		PETALS = "I showed those flowers who's boss. Me. It was me.",
		PETALS_EVIL = "I could normally hold these but because of this mortal fleshsuit I can't.",
		PHLEGM = "Why am I holding this? Ew.",
		PICKAXE = "Iconic, isn't it?",
		PIGGYBACK = "I feel kinda bad for that. No I don't, that was a lie.",
		PIGHEAD = "Looks like an offering to the beast. I like it.",
		PIGHOUSE =
		{
			FULL = "There's certainly someone in there.",
			GENERIC = "These pigs have pretty fancy houses. For pigs.",
			LIGHTSOUT = "Come ON! I know you're home! How rude!",
		},
		PIGKING = "Look at all that flesh....",
		PIGMAN =
		{
			DEAD = "Someone should tell his family.",
			FOLLOWER = "He's part of my entourage.",
			GENERIC = "They kind of creep me out.",
			GUARD = "He looks serious and deadly - something that normally doesn't go well together.",
			WEREPIG = "He's certainly not friendly!",
		},
		PIGSKIN = "It still has the tail on it.",
		PIGTENT = "Smells like bacon. I like.",
		PIGTORCH = "Sure looks cozy.",
		PINECONE = 
		{
		    GENERIC = "I can hear a tiny tree inside it, trying to get out.",
		    PLANTED = "It'll be a tree soon!",
		},
		PITCHFORK = "Isn't this something demons supposedly use?",
		PLANTMEAT = "Leafy greens on meat? No thanks!",
		PLANTMEAT_COOKED = "At least it's warm now...",
		PLANT_NORMAL =
		{
			GENERIC = "Leafy!",
			GROWING = "Guh! It's growing so slowly! Time works so differently for mortals.",
			READY = "Mmmm. Ready to harvest.",
		},
		POMEGRANATE = "It looks like the inside of an alien's brain.",
		POMEGRANATE_COOKED = "Haute Cuisine!",
		POMEGRANATE_SEEDS = "It's a seed.",
		POND = "I wonder if Lizzie's down there.",
		POOP = "Why is this in my pockets? Humans and their fecal matter, goodness.",
		PUMPKIN = "It's large and orange.",
		PUMPKINCOOKIE = "I cooked it myself!",
		PUMPKIN_COOKED = "How did it not turn into a pie?",
		PUMPKIN_LANTERN = "TooSpookyFiveMe! ... That's what you humans say, right?",
		PUMPKIN_SEEDS = "It's a seed.",
		PURPLEAMULET = "It's talking to me.",
		PURPLEGEM = "It contains the mysteries of the universe. That being, very few.",
		RABBIT =
		{
			GENERIC = "He's looking for carrots.",
			HELD = "Do you like death? I think you'd like it.",
		},
		RABBITHOLE = "That must lead to the Kingdom of the Bunnymen.",
		RAINOMETER = "It measures cloudiness.",
		RATATOUILLE = "I cooked it myself!",
		RAZOR = "A sharpened rock tied to a stick. Hygienic!",
		REDGEM = "It sparkles with inner warmth.",
		RED_CAP = "It smells funny.",
		RED_CAP_COOKED = "It's different now...",
		RED_MUSHROOM =
		{
			GENERIC = "It's a mushroom.",
			INGROUND = "It's sleeping.",
			PICKED = "I wonder if it will come back?",
		},
		REEDS =
		{
			BURNING = "That's really burning!",
			GENERIC = "It's a clump of reeds.",
			PICKED = "I picked all the useful reeds.",
		},
        RELIC = 
        {
            GENERIC = "Ancient household goods.",
            BROKEN = "Nothing to work with here.",
        },
        RUINS_RUBBLE = "This can be fixed.",
        RUBBLE = "Just bits and pieces of rock.",
		RESEARCHLAB = "It breaks down objects into their scientific components.",
		RESEARCHLAB2 = "It's even more science-y than the last one!",
		RESEARCHLAB3 = "What have I created?",
		RESEARCHLAB4 = "Who would name something that?",
		RESURRECTIONSTATUE = "Looks like dark magic. I like it.",
		RESURRECTIONSTONE = "Such a touching stone.",
		ROBIN =
		{
			GENERIC = "Does that mean spring is coming?",
			HELD = "He likes my pocket.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Life in the frozen wastes.",
			HELD = "It's so soft.",
		},
		ROBOT_PUPPET = "It's trapped!",
		ROCK_LIGHT =
		{
			GENERIC = "A crusted over lava pit.",
			OUT = "Looks fragile.",
			LOW = "The lava's crusting over.",
			NORMAL = "Nice and comfy.",
		},
		ROCK = "I can't carry that in my mortal fleshsuit.",
		ROCKS = "I can use these.",
        ROOK = "Storm the castle!",
		ROPE = "Some short lengths of rope.",
		ROTTENEGG = "Eww....",
		SANITYROCK =
		{
			ACTIVE = "Nice.",
			INACTIVE = "Looks like a tiny Giza.",
		},
		SAPLING =
		{
			BURNING = "That's burning fast!",
			GENERIC = "It's tiny!",
			PICKED = "That'll teach him.",
		},
		SEEDS = "Each one is a tiny mystery.",
		SEEDS_COOKED = "I cooked all the life out of 'em!",
		SEWING_KIT = "But destruction is so much more fun!!",
		SHOVEL = "There's a lot going on underground.",
		SILK = "It comes from a spider's butt. I have 5000+ years of knowledge to base this upon.",
		SKELETON = "Better him than me.",
		SKULLCHEST = "Looks nice and dangerous.",
		SMALLBIRD =
		{
			GENERIC = "It's cute in a morbid sort of way.",
			HUNGRY = "Looks hungry.",
			STARVING = "Looks like it's starving..",
		},
		SMALLMEAT = "A tiny chunk of dead animal.",
		SMALLMEAT_DRIED = "A little jerky.",
		SPAT = "What a crusty looking animal.",
		SPEAR = "That's one pointy stick.",
		SPIDER =
		{
			DEAD = "Nice.",
			GENERIC = "Spiders are frustratingly boring and also EVERYWHERE.",
			SLEEPING = "I'd better not be here when he wakes up.",
		},
		SPIDERDEN = "Sticky!",
		SPIDEREGGSACK = "I hope these don't hatch in my pocket.",
		SPIDERGLAND = "It has a tangy, antiseptic smell.",
		SPIDERHAT = "I hope I got all of the spider goo out of it.",
		SPIDERQUEEN = "That's... uh... unpleasant...",
		SPIDER_WARRIOR =
		{
			DEAD = "Good riddance!",
			GENERIC = "Looks even meaner than usual.",
			SLEEPING = "I should keep my distance.",
		},
		SPOILED_FOOD = "Disgusting.",
		STATUEHARP = "I appreciate the creativity and also the headless angel.",
		STATUEMAXWELL = "It really captures his personality.",
		STEELWOOL = "It's like a dish scourer.",
		STINGER = "Looks sharp!",
		STRAWHAT = "What a nice hat.",
		STUFFEDEGGPLANT = "I cooked it myself!",
		SUNKBOAT = "It's no use to me out there!",
		SWEATERVEST = "This vest is dapper as all get-out.",
		TAFFY = "I cooked it myself!",
		TALLBIRD = "Looks mad.",
		TALLBIRDEGG = "I want!",
		TALLBIRDEGG_COOKED = "Delicious and nutritional.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Brrrr!",
			GENERIC = "Looks like it's hatching.",
			HOT = "Are eggs supposed to sweat?",
			LONG = "I have a feeling this is going to take a while...",
			SHORT = "It should hatch any time now.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "That's quite an egg!",
			PICKED = "The nest is empty.",
		},
		TEENBIRD =
		{
			GENERIC = "Not a very tall bird.",
			HUNGRY = "I'd better find it some food.",
			STARVING = "It's sizing me up!",
		},
		TELEBASE =
		{
			VALID = "It's ready to go.",
			GEMS = "It needs more purple gems.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks ready.",
			GEMS = "It needs a gem.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "With this I can surely pass through space and time!",
			GENERIC = "This appears to be a nexus to another world!",
			LOCKED = "There's still something missing.",
			PARTIAL = "Soon, my invention will be complete!",
		},
		TELEPORTATO_BOX = "This may control the polarity of the whole universe.",
		TELEPORTATO_CRANK = "Tough enough to handle the most intense experiments.",
		TELEPORTATO_POTATO = "This metal potato contains great and fearful power...",
		TELEPORTATO_RING = "A ring that could focus dimensional energies.",
		TELESTAFF = "It can show me the world.",
		TENT = "I get crazy when I don't sleep.",
		TENTACLE = "That looks dangerous.",
		TENTACLESPIKE = "It's pointy and slimy.",
		TENTACLESPOTS = "I'm... touching tentacle genitals....",
		TENTACLE_PILLAR = "A slimy pole.",
		TENTACLE_PILLAR_ARM = "Little slippery arms.",
		TENTACLE_GARDEN = "Yet another slimy pole.",
		TOPHAT = "I will be the TopHat-Queen!",
		TORCH = "Something to hold back the night.",
		TRAP = "I wove it real tight.",
		TRAP_TEETH = "This is a nasty surprise.",
		TRAP_TEETH_MAXWELL = "That looks dangerous.",
		TREASURECHEST = "It's my tickle trunk!",
		TREASURECHEST_TRAP = "How convenient!",
		TREECLUMP = "It's almost like someone is trying to prevent me from going somewhere.",
		TRINKET_1 = "Some pretty much useless marbles.",
		TRINKET_10 = "Where'd these come from?",
		TRINKET_11 = "He whispers beautiful lies to me.",
		TRINKET_12 = "I'm not sure what I should do with a dessicated tentacle.",
		TRINKET_13 = "It must be some kind of religious artifact.",
		TRINKET_2 = "It's just a cheap replica.",
		TRINKET_3 = "The knot is stuck. Forever.",
		TRINKET_4 = "It must be some kind of religious artifact of the 'Gardener' era.",
		TRINKET_5 = "Even if it were big enough for me to escape from, it wouldn't take me back home.",
		TRINKET_6 = "Their electricity carrying days are over.",
		TRINKET_7 = "Cheap, human entertainment.",
		TRINKET_8 = "Great. All of my tub stopping needs are met.",
		TRINKET_9 = "I'm more of a zipper person, myself.",
		TRUNKVEST_SUMMER = "Wilderness casual.",
		TRUNKVEST_WINTER = "Winter survival gear.",
		TRUNK_COOKED = "I hope he didn't have a cold.",
		TRUNK_SUMMER = "A light breezy trunk.",
		TRUNK_WINTER = "A thick, hairy trunk.",
		TURF_CARPETFLOOR = "It's surprisingly scratchy.",
		TURF_CHECKERFLOOR = "These are pretty snazzy.",
		TURF_DIRT = "A chunk of ground.",
		TURF_FOREST = "A chunk of ground.",
		TURF_GRASS = "A chunk of ground.",
		TURF_MARSH = "A chunk of ground.",
		TURF_ROAD = "Hastily cobbled stones.",
		TURF_ROCKY = "A chunk of ground.",
		TURF_SAVANNA = "A chunk of ground.",
		TURF_WOODFLOOR = "These are floorboards.",
		TURKEYDINNER = "Yum!",
		TWIGS = "It's a bunch of small twigs.",
		UMBRELLA = "This will keep my hair dry, at least. It's something.",
		UNIMPLEMENTED = "It doesn't look finished! It could be dangerous.",
		WAFFLES = "This better be worth it - butter is far too rare!",
		WALL_HAY = "Hmmmm. I guess that'll have to do.",
		WALL_HAY_ITEM = "This seems like a bad idea around Joan...",
		WALL_STONE = "That's a nice wall.",
		WALL_STONE_ITEM = "They make me feel so safe.",
		WALL_RUINS = "An ancient piece of wall.",
		WALL_RUINS_ITEM = "A solid piece of history.",
		WALL_WOOD = "Pointy!",
		WALL_WOOD_ITEM = "Pickets!",
		WALL_MOONROCK = "Spacey and smooth!",
		WALL_MOONROCK_ITEM = "Very light but surprisingly tough.",
		WALRUS = "Walruses are natural predators.",
		WALRUSHAT = "It's covered with walrus hairs. I am disgusted.",
		WALRUS_CAMP =
		{
			EMPTY = "Looks like somebody was camping here.",
			GENERIC = "It looks warm and cozy inside.",
		},
		WALRUS_TUSK = "I'm sure I'll find a use for it eventually.",
		WARG = "You might be something to reckon with, big dog.",
		WASPHIVE = "I think those bees are mad.",
		WETGOOP = "I cooked it myself! I'm am an amazing cook!",
		WINTERHAT = "It'll be good for when winter comes, at least.",
		WINTEROMETER = "I am one heck of a scientist for a demon.",
		WORMHOLE =
		{
			GENERIC = "Soft and undulating.",
			OPEN = "Impulse compels me to jump in.",
		},
		WORMHOLE_LIMITED = "It looks sick.",
		ACCOMPLISHMENT_SHRINE = "I want to use it, and I want the world to know what I did.",        
		LIVINGTREE = "Is it watching me?",
		ICESTAFF = "It's cold to the touch",
		REVIVER = "The beating of this hideous heart will bring a ghost back to life!",
		LIFEINJECTOR = "Booooost!",
		SKELETON_PLAYER =
		{
			MALE = "%s died doing what he loved. Being hurt by %s.",
			FEMALE = "%s died doing what she loved. Being hurt by %s.",
			ROBOT = "%s died doing what it loved. Being hurt by %s.",
		},
		HUMANMEAT = "Flesh is flesh. Where do I draw the line?",
		HUMANMEAT_COOKED = "Cooked nice and pink, but still morally gray.",
		HUMANMEAT_DRIED = "Letting it dry makes it not come from a human, right?",
		MOONROCKNUGGET = "That rock came from the moon.",
	},
	DESCRIBE_GENERIC = "It's a... thing.",
	DESCRIBE_TOODARK = "It's too dark to see!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Mmm. Beaky.",
	},
}
